# Give your microservice an official network name
spring.application.name=customermicroservice
server.port=8081

# MySQL Database Configuration
spring.datasource.url=jdbc:h2:mem:fincore_customer_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Settings (So you can see your data visually)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true